package com.hsp.fitu.entity.enums;

public enum Workout {
    EZ_Bar_Front_Raise,
    ARNOLD_PRESS,
    SHOULDER_PRESS,
    SIDE_LATERAL_RAISE,
    REVERSE_PEC_DECK_FLY,
    FACE_PULL,

    ASSIST_CHIN_AND_DIP,
    PEC_DECK_FLY,
    HAMMER_STRENGTH_FLAT_BENCH_PRESS,
    BENCH_PRESS,
    PUSH_UP,

    ROTARY_PULLDOWN,
    SEATED_ROW,
    LAT_PULLDOWN,
    ASSISTED_CHIN_UP,
    ONE_ARM_DUMBBELL_ROW,
    BARBELL_ROW,
    PULL_UP,

    CABLE_ROPE_PUSHDOWN,
    DUMBBELL_CURL,
    BARBELL_CURL,
    BENCH_DIP,

    V_SQUAT,
    LEG_EXTENSION,
    BACK_EXTENSION,
    POWER_LEG_PRESS,
    LYING_LEG_CURL,
    DUMBBELL_SQUAT,
    BARBELL_SQUAT,
    BARBELL_LUNGE
}
